#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# Import the required libraries.

import json
import matplotlib.pyplot as plt
import pandas as pd

tweets_data_path = './t_raw/test.json'

tweets_data = []
tweets_file = open(tweets_data_path, "r")
for line in tweets_file:
    try:
        tweet = json.loads(line)
        tweets_data.append(tweet)
    except:
        continue
### print 'Tweets= ',len(tweets_data)

tweets = pd.DataFrame(tweets_data)

### print (tweets)

### print (tweets.keys())


# Let's check the top 5 records in the Data Set
### print tweets.head(2)
# Similarly let's check the last 2 records in the Data Set
### print tweets.tail(2)

### print tweets['text']

tweets_by_lang = tweets['lang'].value_counts()
print 'num=',tweets_by_lang

# Make the graphs prettier
pd.set_option('display.mpl_style', 'default')

fig, ax = plt.subplots()
ax.tick_params(axis='x', labelsize=15)
ax.tick_params(axis='y', labelsize=10)
ax.set_xlabel('Languages', fontsize=15)
ax.set_ylabel('Number of tweets' , fontsize=15)
ax.set_title('Top 5 languages', fontsize=15, fontweight='bold')
tweets_by_lang[:5].plot(ax=ax, kind='bar', color='red')
